### ISSUE TITLE
No type definitions in the npm release.

### ISSUE THREAD

**Issue by jpinz** [DidoMarchet/vue-3-supabase#2]
Hi!

I'm trying to use this library with my vue3 typescript project, and peering into what's downloaded from NPM it appears to not have the type definitions.
![image](https://user-images.githubusercontent.com/8357054/153693794-067b5276-52cc-4908-a8d7-7a704e15bf7c.png)
It's been a while since I worked with ts, but if a PR would be helpful just let me know and I can give it a shot.

Thanks!

**Comment by DidoMarchet** [comment]
Hi!
Feel free to contribute! 
I appreciate it :fist:
Even because I'm away for some days.

Thanks and kind regards,
Davide

**Comment by DidoMarchet** [comment]
Hi @jpinz .
I added the type definition in https://github.com/DidoMarchet/vue-3-supabase/tree/type-definition/dist/lib (type-definition branch)
Before publish it I want to do a double check.

Have a nice day,

Davide

**Comment by avanturist888** [comment]
Still no types in latest npm version. Any news about "double check"?

**Comment by DidoMarchet** [comment]
Hi @vasia123 in v.2.2.5 you'll find the type definition.

Let me know, thanks and regards,

Davide

<img width="392" alt="Screenshot 2023-04-16 at 17 52 46" src="https://user-images.githubusercontent.com/38940340/232324757-977d6fa0-7626-4a75-9556-85d37ea4b5e3.png">

**Comment by avanturist888** [comment]
@DidoMarchet 

I updated the vue-3-supabase version to 2.2.5, but the error still persists. According to https://stackoverflow.com/questions/38224232/how-to-consume-npm-modules-from-typescript, you need to add `"typings": "./dist/lib/main.d.ts"` to your `package.json`.

To fix this issue locally, I added the following to my `tsconfig.json`:
```json
"paths": {
  "vue-3-supabase": ["./node_modules/vue-3-supabase/dist/lib/main"]
}
```
I also created a new file `src/types/vue-3-supabase.d.ts` with the following content:
```ts
import { IVueSupabase } from 'vue-3-supabase/dist/lib/@types';
import type { SupabaseClient } from "@supabase/supabase-js";

declare module 'vue-3-supabase' {
  const supabasePlugin: IVueSupabase;
  export default supabasePlugin;
  export function useSupabase(): SupabaseClient; // fox for Module '"vue-3-supabase"' has no exported member 'useSupabase'
}
```

However, I encountered an error with the default example from the readme. The parameter `options: {}` gave the error `Type '{}' is not assignable to type 'undefined'`. To fix this, you need to update the `dist/lib/@types/index.d.ts` file to include the proper options type:

```ts
...
import type { SupabaseClientOptions } from "@supabase/supabase-js";
....
export interface Params {
    ...
    options?: SupabaseClientOptions<'public'>;
}
...
```
Additionally, you need to add a `default export supabasePlugin` and `useSupabase` types to the `dist/lib/main.d.ts` file:

```ts
...
declare const supabasePlugin: IVueSupabase;
export default supabasePlugin;
// Add the export for useSupabase
export function useSupabase(): IVueSupabase;
```

If you are too busy, I can create a pull request.

**Comment by DidoMarchet** [comment]
Hi @vasia123 thanks to the updates!
Sure feel free to create a PR and submit it!

Thanks in advance and kind regards!
