### ISSUE TITLE
What is the usefulness of "Wrapper around Supabase.js"?

### ISSUE THREAD

**Issue by riodw** [DidoMarchet/vue-3-supabase#3]
I've seen a few of these Vue wrappers for Supabase, but I have not seen an explanation as to why one would want to use them.
Can someone point me to what the differences are or even better, why using `vue-3-supabase` is better?

------------------

Why is doing...
```html
<script setup lang="ts">
import { useSupabase } from "vue-supabase";

const supabase = useSupabase();

const { data, error } = await supabase.from("events").select("*");
</script>
```
better than doing...
```html
<script setup lang="ts">
import { supabase } from "../supabase";

const { data, error } = await supabase.from("events").select("*");
</script>
```
?

_I apologize ahead of time if the answer here is simple and I just missed it._

**Comment by DidoMarchet** [comment]
IMO in this case it's useful for lazy people who do not want to write [the initialization](https://github.com/DidoMarchet/vue-3-supabase/blob/main/lib/main.ts).

In general use composable function (useFunction...) can help if you need to access to reactive elements or to extend functionality.

:D btw good question

**Comment by riodw** [comment]
Thank you for your answer!
Got another question for ya, is there a way to inject this package?
_Example:_
```javascript
import { inject } from "vue";
const sb = inject("useSupabase");
```

**Comment by riodw** [comment]
@DidoMarchet  Thank you for your answer!
Got another question for ya, is there a way to inject this package?
_Example:_
```javascript
import { inject } from "vue";
const sb = inject("useSupabase");
```
Also, might you have any example projects using `vue-supabase`?

**Comment by DidoMarchet** [comment]
Hi @riodw 

> Also, might you have any example projects using `vue-supabase`?
Sincerely no :D, or rather I've got my test/dev area. But at work we use other tools.

Regards,

Davide
